/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ilaguna_metrics_ProcessInfo */

#ifndef _Included_com_ilaguna_metrics_ProcessInfo
#define _Included_com_ilaguna_metrics_ProcessInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ilaguna_metrics_ProcessInfo
 * Method:    getPid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ilaguna_metrics_ProcessInfo_getPid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
